server:
  port: 8888

security:
  basic:
    enabled: false

spring: 
  application: 
    name: config-service
  cloud:
    config: 
      label: dev
      server: 
        git: 
          uri: https://gitlab.com/revature_hydra/hydra-configuration.git
          username: revdum
          password: p4ssw0rd



