server:
  port: 8888

security:
  basic:
    enabled: false

spring:
  profiles:
    active: native
  application: 
    name: config-service
  cloud:
    config:
      server: 
        native: 
          searchLocations: file:///${user.dir}/../hydra-configurationBAM
          
#          searchLocations: file:///${user.home}/Desktop/git/BAM/hydra-configurationBAM