server:
  port: 80

security:
  basic:
    enabled: false

spring:
#  profiles:
#    active: native
  application: 
    name: hydra-config-service
  cloud:
    config:
      server: 
        native: 
          searchLocations: file:///${user.dir}/../hydra-configurationBAM