spring:
  profiles:
    active: dev
  application: hydra-config-service

security:
  basic:
    enabled: false
---

spring:
  profiles: prod
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/revature1802Feb12USF/hydra-configurationBAM.git

server:
  port: 80

---

spring:
  profiles: dev
  cloud:
    config:
      server:
        native: 
          searchLocations: file:///${user.dir}/../hydra-configurationBAM
  
server:
  port: 8888



