server:
  port: 80

security:
  basic:
    enabled: false

spring:
#  profiles:
#    active: native
  application: 
    name: config-service
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/revature1802Feb12USF/hydra-configurationBAM.git