server:
  port: 8888

security:
  basic:
    enabled: false

spring: 
  application: 
    name: config-service
  cloud:
    config: 
      server: 
        git: 
          uri: https://github.com/revature1802Feb12USF/hydra-configurationBAM